# ~/dotfiles/.config/alacritty/alacritty.toml
# Target platform: Ubuntu + i3

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x9a9a99"
blue = "0x1984e9"
cyan = "0x398280"
green = "0x00813c"
magenta = "0xfe2c79"
red = "0xfe2626"
white = "0xfdfdc5"
yellow = "0xd08341"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.dim]
black = "0x26282c"
blue = "0x4878bc"
cyan = "0x67a0b2"
green = "0x70c43f"
magenta = "0x98719f"
red = "0xff615c"
white = "0xc5c8c6"
yellow = "0xd0b343"

[colors.normal]
black = "0x202020"
blue = "0x4878bc"
cyan = "0x67a0b2"
green = "0x70c43f"
magenta = "0x98719f"
red = "0xff615c"
white = "0xc5c8c6"
yellow = "0xd0b343"

[colors.primary]
background = "0x202020"
foreground = "0xd4d7d5"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
opacity = 1

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 10
y = 10
